config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :conversations do
    resources :messages
  end

  resources :beers
  resources :games
  resources :bars

  get 'friends', to: 'friends#index', as: 'friends'
  get 'profile', to: 'friends#show', as: 'profile'
  # get 'bar', to: 'bar#show', as: 'bar'
  get 'barcode/:id', to: 'bars#barcode', as: 'barcode'
  get 'new_post', to: 'pages#new_post', as: 'new_post'
  put 'update_post', to: 'pages#update_post', as: 'update_post'
  post "create_beer/:id", to: 'beers#create_beer', as: 'create_beer'
  delete "delete_beer/:id", to: 'beers#delete_beer', as: 'delete_beer'
  get 'video', to: 'pages#video', as: 'video'
  get 'reset_barcodes', to: 'bars#reset_barcodes', as: 'reset_barcodes'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @users = User.all # agregar un filtro para que solo sean los de ese bar
    @conversation = Conversation.new
    @beer = Beer.new
    @beers = Beer.all
  end

  def show
    if params[:sender_id].nil? && params[:recipient_id].nil?
      @user = User.find(params[:format])
    else
      @user = User.find(params[:sender_id], params[:recipient_id])
    end
    @conversation = Conversation.new
    @beer = Beer.new
    @beers = Beer.all
  end
end

app/views/friends/index.html.erb
<div class="container mt-4">
  <%# <h3>All Users</h3> %>

  <div class="notification user-card">
    <%= link_to edit_user_registration_path do %>
      <% if current_user.photo.key != nil %>
        <%= cl_image_tag current_user.photo.key, class: "avatar-xxl" %>
      <% else %>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar-xxl" %>
      <% end %>
    <% end %>
    <div class="notification-content">
      <%= link_to edit_user_registration_path do %>
        <p><strong><%= current_user.name %></strong></p>
      <% end %>
    </div>

    <div class="notification-actions d-flex flex-column align-items-center justify-items-center">
      <div class="mb-2 mt-2">
        <%= link_to conversations_path do  %>
          <i class="fa-sharp fa-solid fa-comment-dots" style="margin-left: 0;"></i>
        <% end %>

        <%= link_to beers_path do  %>
          <i class="fa-solid fa-beer-mug-empty"></i>
        <% end %>
      </div>

      <%= link_to "#" do  %>
        <i class="fa-sharp fa-solid fa-gamepad" style="margin-left: 0;"></i>
      <% end %>

    </div>
  </div>

  <div class="list">

   <% @users.each do |user| %>
    <% if user.id != current_user.id %>

        <div class="notification">
          <%= link_to profile_path(recipient_id: user.id) do %>
            <% if user.photo.key != nil %>
              <%= cl_image_tag user.photo.key, class: "avatar-xl" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar-xl" %>
            <% end %>
          <% end %>
          <div class="notification-content">
            <%= link_to profile_path(recipient_id: user.id) do %>
              <p><strong><%= user.name %></strong> (<%= user.age %>)</p>
            <% end %>
          </div>

          <div class="notification-actions">
            <%= simple_form_for @conversation do |f| %>
              <%= hidden_field_tag(:sender_id, current_user.id) %>
              <%= hidden_field_tag(:recipient_id, user.id) %>
              <%= f.button :button, style: "padding:0;" do %>
                <i class="fa-sharp fa-solid fa-comment-dots" ></i>
              <% end %>
            <% end %>

            <% @beerTarget = @beers.where(sender_id: current_user.id, recipient_id: user.id).first  %>

            <% if @beerTarget.present? %>
              <div data-controller="beer-delete">
                <%= simple_form_for @beerTarget, url: beer_path(@beerTarget), method: :delete do |f| %>
                  <%= hidden_field_tag(:sender_id, current_user.id) %>
                  <%= hidden_field_tag(:recipient_id, user.id) %>
                  <%= f.button :button, style: "padding:0;" do %>
                    <i class="fa-solid fa-champagne-glasses" data-beer-delete-target="remove" data-action="click->beer-delete#removeBeer"></i>
                  <% end %>
                <% end %>
              </div>

              <%# <div data-controller="beer-delete"> %>
                <%#= link_to beer_path(@beerTarget), data: {turbo_method: :delete} do %>
                  <%# <i class="fa-solid fa-champagne-glasses" style="padding:0;" data-beer-delete-target="remove" data-action="click->beer-delete#removeBeer"></i> %>
                <%#end %>
              <%# </div> %>

            <% else %>
              <div data-controller="beer-icon">
                <%= simple_form_for @beer do |f| %>
                  <%= hidden_field_tag(:sender_id, current_user.id) %>
                  <%= hidden_field_tag(:recipient_id, user.id) %>
                  <%= f.button :button, style: "padding:0;" do %>
                    <i class="fa-solid fa-beer-mug-empty" data-beer-icon-target="beer" data-action="click->beer-icon#addBeer"></i>
                  <% end %>
                <% end %>
              </div>
            <% end %>

            <%= link_to "#" do  %>
              <i class="fa-sharp fa-solid fa-gamepad" ></i>
            <% end %>
          </div>
        </div>

    <% end %>
  <% end %>
 </div>
</div>