config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :conversations do
    resources :messages
  end

  resources :beers
  resources :games
  resources :bars

  get 'friends', to: 'friends#index', as: 'friends'
  get 'profile', to: 'friends#show', as: 'profile'
  # get 'bar', to: 'bar#show', as: 'bar'
  get 'barcode/:id', to: 'bars#barcode', as: 'barcode'
  get 'new_post', to: 'pages#new_post', as: 'new_post'
  put 'update_post', to: 'pages#update_post', as: 'update_post'
  post "create_beer/:id", to: 'beers#create_beer', as: 'create_beer'
  delete "delete_beer/:id", to: 'beers#delete_beer', as: 'delete_beer'
  get 'video', to: 'pages#video', as: 'video'
  get 'reset_barcodes', to: 'bars#reset_barcodes', as: 'reset_barcodes'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-danger" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_nabvar-empty.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js">
</script>

app/views/shared/_navbar-main.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style = "padding-top: 10px; padding-bottom: 10px;">
  <div class="container-fluid">
    <div class= "d-flex align-items-center">

        <%# <%= link_to edit_user_registration_path, class: "navbar-photo" do %>
          <%# <% if current_user.photo.key != nil %>
            <%# <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle" %>
          <%# <% else %>
            <%# <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar dropdown-toggle" %>
          <%# <% end %>
        <%# <% end %>

        <div class="nav-item dropdown">
              <% if current_user.photo.key != nil %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit User", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </div>
        </div>

      <h1>BREAKIT</h1>
    </div>

    <div class="d-flex align-items-center navbar-icons" style="padding-bottom: 10px;">
      <%# BEER NOTIFICATION %>
      <div id="beer-notice">
        <% if @beer_read == [] %>
          <%= link_to beers_path do %>
            <%= image_tag('beer', style: "margin-top: 10px;") %>
          <% end %>
        <% else %>
          <%= link_to beers_path do %>
            <%= image_tag('beer-notification', style:"margin-top: 3px;") %>
          <% end %>
        <% end %>
      </div>

      <%# GAMES NOTIFICATION %>
      <div id="game-notice">
        <% if @games_read == [] %>
          <%= link_to games_path do %>
            <%= image_tag('dice', style: "margin-top: 10px;") %>
          <% end %>
        <% else %>
          <%= link_to games_path do %>
            <%= image_tag('dice-notification', style:"margin-top: 3px;") %>
          <% end %>
        <% end %>
      </div>

      <%# CONVERSATION NOTIFICATION %>
      <div id="conversation-notice">
        <% if @conv_read == [] %>
          <%= link_to conversations_path do %>
            <%= image_tag('chat', style: "margin-top: 10px;") %>
          <% end %>
        <% else %>
          <%= link_to conversations_path do %>
            <%= image_tag('chat-notification', style:"margin-top: 3px;") %>
          <% end %>
        <% end %>

      </div>
    </div>

  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js">
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class= "d-flex align-items-center">
      <%= link_to home_path, class: "navbar-brand" do %>
        <%= image_tag("breakit-solo") %>
      <% end %>
      <h1 style= "margin-bottom: 0; font-size: 24px; font-family: 'Share Tech Mono', monospace;">BREAK IT</h1>
    </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="d-flex align-items-center">
            <li class="nav-item dropdown">
              <% if current_user.photo.key != nil %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>

              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Edit User", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item active">
              <%= link_to edit_user_registration_path, class: "nav-link" do %>
                <strong><p class="mb-0" style="margin-left: 10px;"><%= current_user.name%></p></strong>
              <% end %>
            </li>
          </div>
          <li class="nav-item active">
            <%= link_to "Home", home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Discover", bar_path(current_user.bar_code), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Conversations", conversations_path, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>