config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :conversations do
    resources :messages
  end

  resources :beers
  resources :games
  resources :bars

  get 'friends', to: 'friends#index', as: 'friends'
  get 'profile', to: 'friends#show', as: 'profile'
  # get 'bar', to: 'bar#show', as: 'bar'
  get 'barcode/:id', to: 'bars#barcode', as: 'barcode'
  get 'new_post', to: 'pages#new_post', as: 'new_post'
  put 'update_post', to: 'pages#update_post', as: 'update_post'
  post "create_beer/:id", to: 'beers#create_beer', as: 'create_beer'
  delete "delete_beer/:id", to: 'beers#delete_beer', as: 'delete_beer'
  get 'video', to: 'pages#video', as: 'video'
  get 'reset_barcodes', to: 'bars#reset_barcodes', as: 'reset_barcodes'
end

app/views/pages/home.html.erb
<div class="home text-center d-flex" style="background-color: black; height: 100vh;margin: 0; padding: 0; ">
  <div class="mt-5 container d-flex flex-column p-4">
    <div class="header-home d-flex">
      <h1>BREAKIT</h1>
      <%= image_tag("breakit-small")%>
    </div>
    <h2 class="mb-3 subtitle-home">Conect with the people aroud you</h2>
    <div class="container d-flex flex-column pl-5 pr-5 mb-5" style="align-items: center; justify-content: space-around;">
      <%= link_to 'Register', new_user_registration_path, class: "white-round-filled-big-btn mb-3", id: "registration-btn" %>
      <%= link_to 'Login', new_user_session_path, class: "white-outlined-big-btn", id: "login-btn" %>
    </div>

  </div>
</div>

<script>
  // ------------- REGISTRATION BUTTON ------------- //
  const registrationBtn = document.getElementById('registration-btn');
  registrationBtn.addEventListener('click', () => {
    setTimeout(() => {
      location.reload();
    }, 500);
  });

  // ------------- LOGIN BUTTON ------------- //
  const logInBtn = document.getElementById('login-btn');
  logInBtn.addEventListener('click', () => {
    setTimeout(() => {
      location.reload();
    }, 500);
  });

</script>

app/views/pages/new_post.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

      <div class="col-1 d-flex justify-content-center">
        <%= link_to home_path, class: "navbar-brand" do %>
          <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        <% end %>
      </div>

      <div class="col-11 p-2 d-flex justify-content-start" style="margin-left: -5px;">
        <%= image_tag("breakit-small", class:"navbar-logo")%>
        <h1 style="margin-left: 5px;">BREAKIT</h1>
      </div>
</div>

<div class="hiddden" id="hidden-div"></div>
<div>
  <% if @user.photo.key != nil %>

    <%= cl_image_tag current_user.photo.key, id:"first-photo" %>
    <img class= "user-photo d-none" id="user-photo">

    <div>
      <%= simple_form_for(@user, url: update_post_path(@user),html: { method: :put }) do |f| %>
        <%= f.error_notification %>
        <%= f.input :photo, input_html: { class: 'd-none'}, label: false %>
        <%= f.input :photo, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: image_tag('upload-photo.png')  %>
    </div>

        <%= f.input :description,
            required: false,
            label: "Post a comment",
            input_html: { autocomplete: "about-me" },
            placeholder: "Add a post" %>

          <div class="d-flex justify-content-center">
          <div class="form-actions">
            <%= f.button :submit, "Post", class: "white-round-filled-btn", style: "padding-right: 10px; padding-left: 10px; width: 103px; height: 41px; margin-top: 20px;" %>
          </div>
        </div>
      <% end %>

  <% else %>

    <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", id:"first-photo" %>
    <img class= "user-photo d-none" id="user-photo">

    <div>
      <%= simple_form_for(@user, url: update_post_path(@user),html: { method: :put }) do |f| %>
        <%= f.error_notification %>
        <%= f.input :photo, input_html: { class: 'd-none'}, label: false %>
        <%= f.input :photo, input_html: { class: 'd-none', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: image_tag('upload-photo.png')  %>
    </div>

        <%= f.input :description,
        required: false,
        label: "Post a comment",
        input_html: { autocomplete: "about-me" },
        placeholder: "Add a post" %>

          <div class="d-flex justify-content-center">
          <div class="form-actions">
            <%= f.button :submit, "Post", class: "white-round-filled-btn", style: "padding-right: 10px; padding-left: 10px; width: 103px; height: 41px; margin-top: 20px;" %>
          </div>
        </div>
      <% end %>
  <% end %>
</div>


<script>
// ---------------- IMAGE PREVIEW -------------------------------//

  const previewImageOnFileSelect = () => {
  // we select the photo input
  const input = document.getElementById('photo-input');
    // we add a listener to know when a new picture is uploaded
    input.addEventListener('change', () => {
      // we call the displayPreview function (who retrieve the image url and display it)
      displayPreview(input);
    })
}

const displayPreview = (input) => {
    const reader = new FileReader();
    reader.onload = (event) => {
      document.getElementById('user-photo').src = event.currentTarget.result;
    }
    reader.readAsDataURL(input.files[0])
    document.getElementById('user-photo').classList.remove('d-none');
    document.getElementById('first-photo').classList.add('d-none');
}

if (window.location.href.includes("new_post")) {
  previewImageOnFileSelect()
}

  // ---------------- RELOAD PAGE -------------------------------//
    if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }
    else
      localStorage.removeItem('firstLoad');
  }

</script>

app/views/pages/video.html.erb
<%# ----------------- NAVBAR --------------------------------------- %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="col-1 d-flex justify-content-center">
        <%= link_to home_path, class: "navbar-brand", id:"back-btn" do %>
          <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        <% end %>
      </div>

      <div class="col-10 d-flex justify-content-center">
        <p style= "margin: 0; font-size: 16px; color: white; margin-left: -20px;">Video</h1>
      </div>

      <div class="col-1 d-flex justify-content-center">
        <%= link_to new_post_path, class: "navbar-brand", id: "close-button" do %>
          <svg width="30" height="29" viewBox="0 0 30 29" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M16.9887 14.4999L22.5551 9.11906C22.8193 8.86413 22.9679 8.5182 22.9682 8.15737C22.9685 7.79653 22.8205 7.45035 22.5568 7.19498C22.2931 6.9396 21.9353 6.79595 21.562 6.79564C21.1887 6.79532 20.8306 6.93835 20.5664 7.19328L15 12.5741L9.43359 7.19328C9.16941 6.9379 8.81111 6.79443 8.4375 6.79443C8.06389 6.79443 7.70558 6.9379 7.4414 7.19328C7.17722 7.44865 7.02881 7.79501 7.02881 8.15617C7.02881 8.51732 7.17722 8.86368 7.4414 9.11906L13.0078 14.4999L7.4414 19.8808C7.17722 20.1362 7.02881 20.4825 7.02881 20.8437C7.02881 21.2048 7.17722 21.5512 7.4414 21.8066C7.70558 22.0619 8.06389 22.2054 8.4375 22.2054C8.81111 22.2054 9.16941 22.0619 9.43359 21.8066L15 16.4257L20.5664 21.8066C20.8306 22.0619 21.1889 22.2054 21.5625 22.2054C21.9361 22.2054 22.2944 22.0619 22.5586 21.8066C22.8228 21.5512 22.9712 21.2048 22.9712 20.8437C22.9712 20.4825 22.8228 20.1362 22.5586 19.8808L16.9887 14.4999Z" fill="white"/>
          </svg>
        <% end %>
      </div>
</div>

<%# ----------------- MAIN --------------------------------------- %>
<div class="container d-flex justify-content-center">

  <video width="330" height="550" controls="controls" autoplay="true" muted="muted" id="video" loop="loop">
      <source src="https://res.cloudinary.com/dgmtchxjj/video/upload/v1671717764/production/breakit-video_quhge5.mp4"/>
      Your browser does not support the video tag.
  </video>

</div>

<script>
  // ----------------- AUTOPLAY VIDEO -------------------------------//
    document.getElementById('video').play();

  // ---------------- RELOAD PAGE on close button -------------------------------//
  const closeBtn = document.getElementById('close-button');
  closeBtn.addEventListener('click', () => {
    setTimeout(() => {
      location.reload();
    }, 500);
  });

  // ------------- BACK BUTTON ------------- //
  const backBtn = document.getElementById('back-btn');
  backBtn.addEventListener('click', () => {
    setTimeout(() => {
      location.reload();
    }, 500);
  });
</script>