config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :conversations do
    resources :messages
  end

  resources :beers
  resources :games
  resources :bars

  get 'friends', to: 'friends#index', as: 'friends'
  get 'profile', to: 'friends#show', as: 'profile'
  # get 'bar', to: 'bar#show', as: 'bar'
  get 'barcode/:id', to: 'bars#barcode', as: 'barcode'
  get 'new_post', to: 'pages#new_post', as: 'new_post'
  put 'update_post', to: 'pages#update_post', as: 'update_post'
  post "create_beer/:id", to: 'beers#create_beer', as: 'create_beer'
  delete "delete_beer/:id", to: 'beers#delete_beer', as: 'delete_beer'
  get 'video', to: 'pages#video', as: 'video'
  get 'reset_barcodes', to: 'bars#reset_barcodes', as: 'reset_barcodes'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player1, :foreign_key => :player1_id, class_name: 'User'
  belongs_to :player2, :foreign_key => :player2_id, class_name: 'User'

  has_one :winner, :foreign_key => :winner_id, class_name: 'User'

  # validates_uniqueness_of :player1_id, :scope => :player2_id

  scope :between, -> (player1_id, player2_id) do
    where("(games.player1_id = ? AND games.player2_id =?) OR (games.player1_id = ? AND games.player2_id =?)", player1_id, player2_id, player2_id, player1_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.where("player1_id = ? OR player2_id = ?", current_user, current_user).order(updated_at: :desc)
    @game = Game.new

    @games.each do |game|
      game.read = true
      game.save!
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @player1 = User.find(params[:player1_id]).id
    @player2 = User.find(params[:player2_id]).id
    @game = Game.new(game_params)

    @game.player1_id = @player1
    @game.player2_id = @player2

    if @game.save!
      redirect_to game_path(@game)
      # redirect_to bar_path(current_user.bar_code)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)

    @game.read = false

    winner
    @game.save!
    redirect_to game_path(@game)
  end

  def compareHand(handA, handB)
    if handA == "Paper" && handB == "Rock"
      1
    elsif handA == "Paper" && handB == "Scissors"
      2
    elsif handA == "Rock" && handB == "Paper"
      2
    elsif handA == "Rock" && handB == "Scissors"
      1
    elsif handA == "Scissors" && handB == "Paper"
      1
    elsif handA == "Scissors" && handB == "Rock"
      2
    elsif handA == handB
      3
    end
  end

  def winner
    hand1 = @game.hand1
    hand2 = @game.hand2
    hand3 = @game.hand3
    hand4 = @game.hand4
    hand5 = @game.hand5
    hand6 = @game.hand6

    a = [
      compareHand(hand1, hand2),
      compareHand(hand3, hand4),
      compareHand(hand5, hand6)
    ]

    if a.count(1) > a.count(2) && a.count(1) > a.count(3) || a.count(3) == 2 && a.count(1) == 1 # gana el 1
      @game.winner_id = @game.player1_id
    elsif a.count(2) > a.count(1) && a.count(2) > a.count(3) || a.count(3) == 2 && a.count(2) == 1 # gana el 2
      @game.winner_id = @game.player2_id
    elsif a.count(1) == a.count(2) && a.count(3) == 1 || a.count(3) == 3 #empate
      @game.winner_id = @game.player1_id
      @game.draw = "Draw"
    end
  end

  private

  def game_params
    params.require(:game).permit(:hand1, :hand2, :hand3, :hand4, :hand5, :hand6)
  end
end

app/views/games/edit.html.erb
<%# ------------------------NAVBAR-------------------- %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="col-1 d-flex justify-content-center">
    <button onclick="history.back()" style="background:none; border:none">
      <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>
  </div>
  <div class="col-11 d-flex justify-content-center">
    <p style= "margin: 0; font-size: 16px; color: white; margin-left: -20px;">Game</h1>
  </div>
</div>

<%# ------------------------MAIN-------------------- %>

<div class="container mt-3">
    <% if @game.winner_id == nil %>

      <% if User.find(@game.player1_id) == current_user %>
        <% opponent = User.find(@game.player2_id) %>
      <% else %>
        <% opponent = User.find(@game.player1_id) %>
      <% end %>

      <%# <div class="container d-flex align-items-center" style="margin-bottom: 30px; margin-top: 30px;"> %>
        <%# if opponent.photo.key != nil %>
          <%#= cl_image_tag opponent.photo.key, class:"avatar-large", style:"margin-right:15px;" %>
        <%# else %>
          <%#= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class:"avatar-large" %>
        <%# end %>
      <%# </div> %>

      <div class="container mt-3">
        <div class="messages text-center bg-black">
          <p style="margin-bottom: 2rem; color: white; font-weight: 700; font-size: 16px;">Make 3 moves</p>
            <%= simple_form_for @game do |f| %>

              <div class="field">
                <p style="color: white" class="m-0 p-0 align-self-center ">1º</p>
                <%= f.collection_radio_buttons(:hand2, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand2| %>
                  <div class="rounded-circle p-1 hand2">
                  <%= hand2.label {image_tag("#{hand2.text}.png")}  %>
                  </div>
                  <%= hand2.radio_button class:"d-none"%>
                <% end %>
              </div>

              <div class="field">
                <p style="color: white" class="m-0 p-0 align-self-center ">2º</p>
                <%= f.collection_radio_buttons(:hand4, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand4| %>
                  <div class="rounded-circle p-1 hand4">
                  <%= hand4.label {image_tag("#{hand4.text}.png")}  %>
                  </div>
                  <%= hand4.radio_button class:"d-none"%>
                <% end %>
              </div>

              <div class="field">
                <p style="color: white" class="m-0 p-0 align-self-center ">3º</p>
                <%= f.collection_radio_buttons(:hand6, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand6| %>
                  <div class="rounded-circle p-1 hand6">
                  <%= hand6.label {image_tag("#{hand6.text}.png")}  %>
                  </div>
                  <%= hand6.radio_button class:"d-none"%>
                <% end %>
              </div>

              <div>
                <%= f.button :submit, "Let's play", class: "white-round-filled-btn", style: "padding-right: 10px; padding-left: 10px; width: 103px; height: 41px; margin-top: 20px; background-color: #5A81E3; border: none; color: white; font-weight: 600;"%>
              </div>
            <% end %>
        </div>
      </div>

    <% else %>
      <div class="container d-flex align-items-center">
        <p style="color:white;">Play has ended, please start a new game</p>
      </div>

    <% end %>
</div>

<%# ------------------------RELOAD-------------------- %>

<script>
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
</script>

app/views/games/index.html.erb
<%# ------------------------NAVBAR-------------------- %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="col-1 d-flex justify-content-center">
    <button onclick="history.back()" style="background:none; border:none">
      <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>
  </div>
  <div class="col-11 d-flex justify-content-center">
    <p style= "margin: 0; font-size: 16px; color: white; margin-left: -20px;">Games</h1>
  </div>
</div>

<%# ------------------------MAIN-------------------- %>
<% @game_check = @games.where(player1_id: current_user.id).first || @games.where(player2_id: current_user.id).first %>
<% if @game_check != nil %>
  <div class="container">
    <div class="list" style="overflow: scroll; height: 92vh;">

      <% @games.each do |game| %>
        <%# if game.player1_id == current_user.id || game.player2_id == current_user.id %>
          <% if game.player1_id == current_user.id %>
            <% opponent = User.find(game.player2_id) %>
          <% else %>
            <% opponent = User.find(game.player1_id) %>
          <% end %>

          <div class="notification">
            <% if opponent.photo.key != nil %>

              <div class="col-2">
                <% if game.player1_id == current_user.id %>
                  <%= link_to profile_path(player2_id: opponent.id) do %>
                    <%= cl_image_tag opponent.photo.key, class: "avatar-large" %>
                  <% end %>
                <% else %>
                  <%= link_to profile_path(player1_id: opponent.id) do %>
                    <%= cl_image_tag opponent.photo.key, class: "avatar-large" %>
                  <% end %>
                <% end %>
              </div>

              <div class="notification-content d-flex flex-column col-7">
                <strong><%= link_to "#{opponent.name}", profile_path(sender_id: opponent.id), style:"margin-right: 15px;" %></strong>
                <% if game.winner_id == nil %>
                  <% if game.player2_id == current_user.id %>
                    <p style="color: #5A81E3; font-size: 15px;">It is your turn</p>
                  <% else %>
                    <p style="font-size: 15px;">It is <%= User.find(game.player2_id).name %>'s turn</p>
                  <% end %>
                <% else %>
                  <% if game.draw == nil %>
                    <% if User.find(game.winner_id) == current_user %>
                      <p style="font-size: 15px; color: green;">You won!</p>
                    <% else %>
                      <p style="font-size: 15px; color: red;">You lost</p>
                    <% end %>
                  <% else %>
                    <p style="font-size: 15px;">It is a draw</p>
                  <% end %>
                <% end %>
              </div>

            <% else %>
              <div class="col-2">
                <% if game.player1_id == current_user.id %>
                  <%= link_to profile_path(player2_id: opponent.id) do %>
                    <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar-large" %>
                  <% end %>
                <% else %>
                  <%= link_to profile_path(player1_id: opponent.id) do %>
                    <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar-large" %>
                  <% end %>
                <% end %>
              </div>

              <div class="notification-content d-flex flex-column col-7">
                <strong><%= link_to "#{opponent.name}", profile_path(sender_id: opponent.id), style:"margin-right: 15px;" %></strong>
                <% if game.winner_id == nil %>
                  <% if game.player2_id == current_user.id %>
                    <p style="color: #5A81E3; font-size: 15px;">It is your turn</p>
                  <% else %>
                    <p style="font-size: 15px;">It is <%= User.find(game.player2_id).name %>'s turn</p>
                  <% end %>
                <% else %>
                  <% if game.draw == nil %>
                    <% if User.find(game.winner_id) == current_user %>
                      <p style="font-size: 15px; color: green;">You won!</p>
                    <% else %>
                      <p style="font-size: 15px; color: red;">You lost</p>
                    <% end %>
                  <% else %>
                    <p style="font-size: 15px; color: red;">It is a draw</p>
                  <% end %>
                <% end %>
              </div>

            <% end %>

            <div class="notification-actions col-3">

              <%# IF THE GAME IS FINISHED %>
              <% if game.winner_id != nil %>
                <div class="d-flex flex-column">
                  <%= link_to new_game_path(player1_id: current_user.id, player2_id: opponent.id) do  %>
                    <p style="font-size: 15px; color: white; text-align: center;">Play again</p>
                  <% end %>
                  <% if game.draw == nil %>
                    <% if User.find(game.winner_id) == current_user %>
                      <p style="font-size: 15px; color: white;">1/0</p>
                    <% else %>
                      <p style="font-size: 15px; color: white;">0/1</p>
                    <% end %>
                  <% else %>
                    <p style="font-size: 15px; color: white;">0/0</p>
                  <% end %>
                </div>


              <%# IF THE GAME IS NOT FINISHED %>
              <% else %>
                <%# if game.hand2 == nil %>
                  <% if game.player2_id == current_user.id %>
                    <%# II. Si vos no lo iniciaste --> te lleva al edit %>
                    <%= link_to edit_game_path(game) do  %>
                      <p class="white-round-filled-btn" style="color: white; width: 70px; height: 30px;background: #5A81E3; font-weight: 600; font-size: 14px; text-align: center;">Play!</p>
                    <% end %>
                  <% else %>
                    <div class="d-flex flex-column">
                      <p style="font-size: 15px; color: white;">Waiting</p>
                      <p style="font-size: 15px; color: white;">Opponent</p>
                    </div>
                    <%# Show Juego %>
                    <%# II. Si vos lo iniciaste --> te lleva al show %>
                    <%#= link_to game_path(game) do  %>
                      <%# <p class="white-round-filled-btn" style="color: white; width: 70px; height: 30px;background: #5A81E3; font-weight: 600; font-size: 14px; text-align: center;">Moves</p> %>
                    <%# end %>
                  <% end %>
                <%# end %>
              <% end %>
            </div>

          </div>
        <%# end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container" style="padding-top: 70px;">
    <p style="color: white; text-align:center; margin-bottom: 0;">No games played yet</p>
    <p style="color: white; text-align:center;">Interact with people around you</p>
  </div>
<% end %>

<%# ------------------------RELOAD-------------------- %>

<script>
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
</script>

app/views/games/new.html.erb
<%# ------------------------NAVBAR-------------------- %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="col-1 d-flex justify-content-center">
    <button onclick="history.back()" style="background:none; border:none">
      <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>
  </div>
  <div class="col-11 d-flex justify-content-center">
    <p style= "margin: 0; font-size: 16px; color: white; margin-left: -20px;">Game</h1>
  </div>
</div>

<%# ------------------------MAIN-------------------- %>
<div class="container bg-black mt-3">
  <% opponent = User.find(params[:player2_id]) %>

  <%# <div class="container d-flex align-items-center"> %>
    <%# if opponent.photo.key != nil %>
      <%#= cl_image_tag opponent.photo.key, class:"avatar-large", style:"margin-right:15px;" %>
    <%# else %>
      <%#= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class:"avatar-large" %>
    <%# end %>
  <%# </div> %>

  <div class="container mt-3">
    <div class="messages text-center bg-black">
      <p style="margin-bottom: 2rem; color: white; font-weight: 700; font-size: 16px;">Make 3 moves</p>
        <%= simple_form_for @game do |f| %>
          <%= hidden_field_tag(:player1_id, current_user.id) %>
          <%= hidden_field_tag(:player2_id, opponent.id) %>
          <div class="field">
            <p style="color: white" class="m-0 p-0 align-self-center ">1º</p>
            <%= f.collection_radio_buttons(:hand1, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand1| %>
              <div class="rounded-circle p-1 hand1">
              <%= hand1.label {image_tag("#{hand1.text}.png")}  %>
              </div>
              <%= hand1.radio_button class:"d-none"%>
            <% end %>
          </div>

          <div class="field">
            <p style="color: white" class="m-0 p-0 align-self-center ">2º</p>
            <%= f.collection_radio_buttons(:hand3, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand3| %>
              <div class="rounded-circle p-1 hand3">
              <%= hand3.label {image_tag("#{hand3.text}.png")}  %>
              </div>
              <%= hand3.radio_button class:"d-none"%>
            <% end %>
          </div>
          <div class="field">
            <p style="color: white" class="m-0 p-0 align-self-center ">3º</p>
            <%= f.collection_radio_buttons(:hand5, [['Rock', 'rock'], ['Paper', 'paper'], ['Scissors', 'scissors']], :first, :last, :item_wrapper_class => 'horizontal') do |hand5| %>
              <div class="rounded-circle p-1 hand5">
              <%= hand5.label {image_tag("#{hand5.text}.png")}  %>
              </div>
              <%= hand5.radio_button class:"d-none"%>
            <% end %>
          </div>
          <div>
            <%= f.button :submit, "Let's play", class: "white-round-filled-btn", style: "padding-right: 10px; padding-left: 10px; width: 103px; height: 41px; margin-top: 20px; background-color: #5A81E3; border: none; color: white; font-weight: 600;"%>
          </div>
        <% end %>
    </div>
  </div>

</div>

<%# ------------------------RELOAD-------------------- %>

<script>
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
</script>

app/views/games/show.html.erb
<%# ------------------------NAVBAR-------------------- %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="col-1 d-flex justify-content-center">
    <button onclick="history.back()" style="background:none; border:none">
      <svg style = "margin-left: 20px;" width="11" height="18" viewBox="0 0 11 18" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 2L2 9L9 16" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </button>
  </div>
  <div class="col-11 d-flex justify-content-center">
    <p style= "margin: 0; font-size: 16px; color: white; margin-left: -20px;">Game</h1>
  </div>
</div>

<%# ------------------------MAIN-------------------- %>

<div class="container mt-3">

  <%# IF THE GAME IS FINISHED %>
  <% if @game.winner_id != nil  %>
    <div class="row d-flex notification">
      <div class="column col-6 text-center">
        <% @player1 = User.find(@game.player1_id) %>
        <%# <p class="mb-2">Player 1</p> %>

        <div class="profile-user">
          <%= link_to profile_path(@player1.id) do %>
            <% if @player1.photo.key != nil %>
              <%= cl_image_tag @player1.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar" %>
            <% end %>
          <% end %>

          <div class="notification-content">
            <%= link_to profile_path(@player1.id) do %>
              <p><strong><%=@player1.name %></strong></p>
            <% end %>
          </div>
        </div>

        <div class="move mt-3">
          <p class="mb-2">Moves:</p>
          <div class="d-flex flex-column align-items-center">
            <% if @game.hand2 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand2 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand2 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>
          </div>
        </div>
      </div>

      <div class="column col-6 text-center">
        <% @player2 = User.find(@game.player2_id) %>
        <%# <p class="mb-2">Player 2</p> %>

        <div class="profile-user">
          <%= link_to profile_path(@player2.id) do %>
            <% if @player2.photo.key != nil %>
              <%= cl_image_tag @player2.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar" %>
            <% end %>
          <% end %>

          <div class="notification-content">
            <%= link_to profile_path(@player2.id) do %>
              <p><strong><%=@player2.name %></strong></p>
            <% end %>
          </div>
        </div>

        <div class="move mt-3">
          <p class="mb-2">Moves:</p>
          <div class="d-flex flex-column align-items-center">
            <% if @game.hand2 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand2 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand2 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand4 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand6 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>
          </div>
        </div>

      </div>
    </div>

    <%# IF THE GAME IS FINISHED AND IT IS NOT A DRAW %>
    <% if @game.draw == nil %>

      <div class="row notification text-center">
        <p class= "mb-2">The winner is</p>
        <% @winner = User.find(@game.winner_id) %>

        <div class="profile-user">
          <%= link_to profile_path(@winner.id) do %>
            <% if @winner.photo.key != nil %>
              <%= cl_image_tag @winner.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar" %>
            <% end %>
          <% end %>

          <div class="notification-content">
            <%= link_to profile_path(@winner.id) do %>
              <p><strong><%=@winner.name %></strong></p>
            <% end %>
          </div>
        </div>

      </div>

    <%# IF THE GAME IS FINISHED AND IT IS A DRAW %>
    <% else %>
      <div class="row notification text-center">
        <strong><p>It is a draw</p></strong>
      </div>
    <% end %>
  <% end %>

  <%# IF THE GAME IS NOT FINISHED %>
  <% if @game.winner_id == nil %>

    <div class="row d-flex notification">
      <div class="column col-6 text-center">
        <% @player1 = User.find(@game.player1_id) %>
        <%# <p class="mb-2">Player 1</p> %>

        <div class="profile-user">
          <%= link_to profile_path(@player1.id) do %>
            <% if @player1.photo.key != nil %>
              <%= cl_image_tag @player1.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar" %>
            <% end %>
          <% end %>

          <div class="notification-content">
            <%= link_to profile_path(@player1.id) do %>
              <p><strong><%=@player1.name %></strong></p>
            <% end %>
          </div>
        </div>

        <div class="move mt-3">
          <p class="mb-2">Moves:</p>
          <div class="d-flex flex-column align-items-center">
            <% if @game.hand1 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand1 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand1 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand3 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand3 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand3 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand5 == "Scissors" %>
              <%= image_tag("scissors", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand5 == "Rock" %>
              <%= image_tag("rock", height: '60', width: '60')%>
            <% end %>

            <% if @game.hand5 == "Paper" %>
              <%= image_tag("paper", height: '60', width: '60')%>
            <% end %>
          </div>
        </div>
      </div>

      <div class="column col-6 text-center">
        <% @player2 = User.find(@game.player2_id) %>
        <%# <p class="mb-2">Player 2</p> %>

        <div class="profile-user">
          <%= link_to profile_path(@player2.id) do %>
            <% if @player2.photo.key != nil %>
              <%= cl_image_tag @player2.photo.key, class: "avatar" %>
            <% else %>
              <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149071.png", class: "avatar" %>
            <% end %>
          <% end %>

          <div class="notification-content">
            <%= link_to profile_path(@player2.id) do %>
              <p><strong><%=@player2.name %></strong></p>
            <% end %>
          </div>
        </div>

        <div class="move mt-3">
          <p class="mb-2">Moves:</p>
          <div class="d-flex flex-column">
            <div style="display: flex; height: 60px; justify-content: center; align-items: flex-end;">
              <i class="fa-solid fa-hourglass-start mb-2" style="font-size: 45px; color: white;"></i>
            </div>
            <div style="display: flex; height: 60px; justify-content: center; align-items: flex-end;">
              <i class="fa-solid fa-hourglass-start mb-2" style="font-size: 45px; color: white;"></i>
            </div>
            <div style="display: flex; height: 60px; justify-content: center; align-items: flex-end;">
              <i class="fa-solid fa-hourglass-start mb-2" style="font-size: 45px; color: white;"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row notification text-center">
      <strong><p>Waiting for opponent to play his/her move</p></strong>
    </div>

  <% end %>
</div>

<%# ------------------------RELOAD-------------------- %>

<script>
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
</script>